/**
 * Changelog entries — newest first.
 * Types: "feature" | "fix" | "improvement" | "breaking"
 */
export const CHANGELOG = [
  {
    version: "0.1.24.1",
    date: "2026-03-25",
    entries: [
      { type: "feature", key: "cl_income_statement_redesign" },
      { type: "feature", key: "cl_balance_sheet_redesign" },
      { type: "feature", key: "cl_affiliation_enriched" },
      { type: "feature", key: "cl_custom_scrollbar" },
      { type: "feature", key: "cl_revenue_integration" },
      { type: "feature", key: "cl_crowdfunding_tva" },
      { type: "feature", key: "cl_crowdfunding_bilan_card" },
      { type: "improvement", key: "cl_shared_components" },
      { type: "improvement", key: "cl_code_review_14_pages" },
      { type: "improvement", key: "cl_print_footer_totals" },
      { type: "improvement", key: "cl_crowdfunding_tiers_enriched" },
      { type: "fix", key: "cl_affiliation_donut_fix" },
      { type: "fix", key: "cl_suspense_flash_fix" },
      { type: "fix", key: "cl_donation_backer_count" },
    ],
  },
  {
    version: "0.1.23.0",
    date: "2026-03-25",
    entries: [
      { type: "feature", key: "cl_equity_refactor" },
      { type: "feature", key: "cl_notification_dots" },
      { type: "feature", key: "cl_esop_auto_captable" },
      { type: "feature", key: "cl_affiliation_charts" },
      { type: "improvement", key: "cl_code_review_fixes" },
      { type: "improvement", key: "cl_terminology_simplification" },
      { type: "improvement", key: "cl_floating_toolbar_capsule" },
      { type: "fix", key: "cl_print_object_fix" },
    ],
  },
  {
    version: "0.1.22.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_bulk_selection" },
      { type: "feature", key: "changelog_page_icons" },
      { type: "feature", key: "changelog_cashflow_statement" },
      { type: "feature", key: "changelog_randomize_all" },
      { type: "improvement", key: "changelog_code_review_v22" },
      { type: "fix", key: "changelog_cfg_showpcmn_fix" },
    ],
  },
  {
    version: "0.1.21.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_cmdk_palette" },
      { type: "feature", key: "changelog_quick_add" },
    ],
  },
  {
    version: "0.1.20.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_accounting_redesign" },
      { type: "feature", key: "changelog_chord_shortcuts" },
      { type: "feature", key: "changelog_command_palette_v2" },
      { type: "improvement", key: "changelog_pcmn_collapsible" },
      { type: "improvement", key: "changelog_kpi_glossary" },
    ],
  },
  {
    version: "0.1.19.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_accounting_full_pcmn" },
      { type: "improvement", key: "changelog_accounting_refacto" },
      { type: "feature", key: "changelog_accounting_classes_35" },
    ],
  },
  {
    version: "0.1.18.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_pcmn_classes_complete" },
      { type: "feature", key: "changelog_shareholder_loans_sync" },
      { type: "feature", key: "changelog_balance_sheet_fields" },
      { type: "improvement", key: "changelog_stocks_card_redesign" },
      { type: "improvement", key: "changelog_kpi_labels_simplified" },
    ],
  },
  {
    version: "0.1.17.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_bfr_ratios" },
      { type: "feature", key: "changelog_financing_plan" },
      { type: "feature", key: "changelog_isoc_provision" },
      { type: "improvement", key: "changelog_real_tva_balance" },
      { type: "improvement", key: "changelog_debt_cashflow" },
      { type: "improvement", key: "changelog_i18n_split" },
      { type: "fix", key: "changelog_financelink_card_title" },
    ],
  },
  {
    version: "0.1.16.2",
    date: "2026-03-23",
    entries: [
      { type: "improvement", key: "changelog_code_review_cleanup" },
      { type: "improvement", key: "changelog_glossary_kpi_tooltips" },
      { type: "fix", key: "changelog_kpicard_color_removal" },
      { type: "fix", key: "changelog_hardcoded_strings" },
      { type: "fix", key: "changelog_financelink_placement" },
    ],
  },
  {
    version: "0.1.16.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_wizard_component" },
      { type: "feature", key: "changelog_stocks_auto_charges" },
      { type: "improvement", key: "changelog_pcmn_roadmap" },
      { type: "improvement", key: "changelog_sidebar_icons" },
      { type: "improvement", key: "changelog_subsidy_auto" },
      { type: "fix", key: "changelog_cfg_cost_modal" },
    ],
  },
  {
    version: "0.1.15.0",
    date: "2026-03-23",
    entries: [
      { type: "feature", key: "changelog_captable_refacto" },
      { type: "improvement", key: "changelog_sidebar_restructure" },
    ],
  },
  {
    version: "0.1.14.0",
    date: "2026-03-22",
    entries: [
      { type: "feature", key: "changelog_income_statement" },
      { type: "feature", key: "changelog_balance_sheet" },
    ],
  },
  {
    version: "0.1.13.0",
    date: "2026-03-22",
    entries: [
      { type: "feature", key: "changelog_stocks_page" },
      { type: "feature", key: "changelog_datepicker" },
      { type: "feature", key: "changelog_chart_palette" },
      { type: "feature", key: "changelog_roadmap_sitemap" },
      { type: "feature", key: "changelog_kpi_glossary" },
      { type: "improvement", key: "changelog_tva_hidden" },
      { type: "improvement", key: "changelog_pcmn_60_64_66_73" },
      { type: "improvement", key: "changelog_crowd_backers" },
      { type: "improvement", key: "changelog_crowd_status" },
      { type: "improvement", key: "changelog_chart_legend_blur" },
      { type: "fix", key: "changelog_code_review_v12" },
    ],
  },
  {
    version: "0.1.12.0",
    date: "2026-03-22",
    entries: [
      { type: "feature", key: "changelog_tva_per_line" },
      { type: "feature", key: "changelog_crowd_lifecycle" },
      { type: "improvement", key: "changelog_crowd_wizard_dates" },
    ],
  },
  {
    version: "0.1.11.0",
    date: "2026-03-22",
    entries: [
      { type: "feature", key: "changelog_crowdfunding_page" },
      { type: "feature", key: "changelog_debt_refactor" },
      { type: "feature", key: "changelog_cashflow_refactor" },
      { type: "improvement", key: "changelog_crowdfunding_wizard" },
      { type: "improvement", key: "changelog_linked_labels" },
      { type: "fix", key: "changelog_code_review_fixes" },
    ],
  },
  {
    version: "0.1.10.0",
    date: "2026-03-22",
    entries: [
      { type: "feature", key: "changelog_salary_rewrite" },
      { type: "feature", key: "changelog_benefits_atn" },
      { type: "feature", key: "changelog_glossary_fab" },
      { type: "improvement", key: "changelog_charges_auto_items" },
      { type: "improvement", key: "changelog_chart_hover" },
      { type: "improvement", key: "changelog_secondary_btn_hover" },
      { type: "improvement", key: "changelog_equipment_layout" },
      { type: "fix", key: "changelog_glossary_welcome" },
    ],
  },
  {
    version: "0.1.9.0",
    date: "2026-03-19",
    entries: [
      { type: "feature", key: "changelog_revenue_table" },
      { type: "improvement", key: "changelog_button_hierarchy" },
      { type: "improvement", key: "changelog_simplified_subtitles" },
    ],
  },
  {
    version: "0.1.8.0",
    date: "2026-03-19",
    entries: [
      { type: "feature", key: "changelog_overview_subpages" },
      { type: "improvement", key: "changelog_i18n_sensitivity" },
      { type: "improvement", key: "changelog_i18n_cashflow" },
      { type: "fix", key: "changelog_portal_overlay" },
    ],
  },
  {
    version: "0.1.7.0",
    date: "2026-03-19",
    entries: [
      { type: "feature", key: "changelog_kpi_engine" },
      { type: "feature", key: "changelog_sensitivity_analysis" },
      { type: "feature", key: "changelog_cashflow_projections" },
      { type: "feature", key: "changelog_revenue_redesign" },
      { type: "feature", key: "changelog_overview_tabs" },
      { type: "feature", key: "changelog_dev_pages" },
      { type: "improvement", key: "changelog_generic_costs" },
      { type: "improvement", key: "changelog_pcmn_sub_sync" },
      { type: "improvement", key: "changelog_dropdown_portal" },
      { type: "improvement", key: "changelog_calculations_cleanup" },
      { type: "fix", key: "changelog_foreach_guard" },
      { type: "fix", key: "changelog_footer_sticky" },
    ],
  },
  {
    version: "0.1.6.0",
    date: "2026-03-18",
    entries: [
      { type: "feature", key: "changelog_breakeven_chart" },
      { type: "feature", key: "changelog_overview_redesign" },
      { type: "improvement", key: "changelog_unified_buttons" },
      { type: "improvement", key: "changelog_wizard_inputs" },
      { type: "improvement", key: "changelog_tooltip_cleanup" },
    ],
  },
  {
    version: "0.1.5.0",
    date: "2026-03-18",
    entries: [
      { type: "feature", key: "changelog_pcmn_complete" },
      { type: "feature", key: "changelog_treasury_wizard" },
      { type: "feature", key: "changelog_per_user_pricing" },
      { type: "feature", key: "changelog_biz_revenue_defaults" },
      { type: "feature", key: "changelog_print_copyright" },
      { type: "improvement", key: "changelog_ratios_generic" },
      { type: "improvement", key: "changelog_revenue_simplified" },
      { type: "improvement", key: "changelog_sidebar_profile" },
      { type: "improvement", key: "changelog_print_unified" },
    ],
  },
  {
    version: "0.1.4.0",
    date: "2026-03-18",
    entries: [
      { type: "feature", key: "changelog_bfr_simulation" },
      { type: "feature", key: "changelog_wizard_revenue" },
      { type: "feature", key: "changelog_wizard_company" },
      { type: "improvement", key: "changelog_amortissement" },
      { type: "improvement", key: "changelog_settings_ux" },
      { type: "fix", key: "changelog_dri_saas" },
      { type: "fix", key: "changelog_profile_placeholders" },
    ],
  },
  {
    version: "0.1.3.0",
    date: "2026-03-18",
    entries: [
      { type: "feature", key: "changelog_salary_sync" },
      { type: "feature", key: "changelog_role_presets" },
      { type: "feature", key: "changelog_equity_activation" },
      { type: "feature", key: "changelog_empty_defaults" },
      { type: "feature", key: "changelog_plan_redaction" },
      { type: "improvement", key: "changelog_terminology" },
      { type: "improvement", key: "changelog_logo_svg" },
    ],
  },
  {
    version: "0.1.2.0",
    date: "2026-03-18",
    entries: [
      { type: "feature", key: "changelog_overview_simple" },
      { type: "feature", key: "changelog_business_type" },
    ],
  },
  {
    version: "0.1.1.0",
    date: "2026-03-18",
    entries: [
      { type: "feature", key: "changelog_revenue_pcmn" },
      { type: "feature", key: "changelog_revenue_categories" },
      { type: "improvement", key: "changelog_component_enhancements" },
      { type: "fix", key: "changelog_sidebar_search_i18n" },
    ],
  },
  {
    version: "0.1.0.0",
    date: "2026-03-18",
    entries: [
      { type: "breaking", key: "changelog_alpha_launch" },
      { type: "feature", key: "changelog_sidebar_nav" },
      { type: "feature", key: "changelog_revenue_streams" },
      { type: "feature", key: "changelog_salary_independant" },
      { type: "feature", key: "changelog_design_system" },
      { type: "feature", key: "changelog_dark_mode" },
      { type: "feature", key: "changelog_dnd_kit" },
      { type: "feature", key: "changelog_font_scale" },
    ],
  },
];
